name: Build APK

on:
  push:
    paths-ignore:
      - 'ios/**'
      - 'readme.md'
  pull_request:
    paths-ignore:
      - 'ios/**'
      - 'readme.md'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout sources
        uses: actions/checkout@v4

      - name: use Node.js 20.x
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: install dependencies
        run: npm ci

      - name: build Nuxt project
        run: npm run generate

      - name: copy to Android project
        run: npx cap sync

      - name: Run static analysis (Gradle action)
        uses: gradle/gradle-build-action@v4
        with:
          cache: true
          cache-dependency-path: |
            android/**/build.gradle
            android/**/build.gradle.kts
            android/**/settings.gradle
            android/**/settings.gradle.kts
            android/gradle/wrapper/gradle-wrapper.properties
          arguments: staticAnalysis -p android --no-daemon

      - name: setup debug keystore
        run: |
          mkdir -p "$HOME/.android"
          cp android/debug.keystore "$HOME/.android/debug.keystore"

      - name: Build Android app (Gradle action)
        uses: gradle/gradle-build-action@v4
        with:
          cache: true
          cache-dependency-path: |
            android/**/build.gradle
            android/**/build.gradle.kts
            android/**/settings.gradle
            android/**/settings.gradle.kts
            android/gradle/wrapper/gradle-wrapper.properties
          arguments: assembleDebug -p android --no-daemon

      - name: rename apk
        working-directory: android/app/build/outputs/apk/debug/
        run: |
          build="$(date +%Y%m%d-%H%M%S)-$(git rev-parse --short HEAD)"
          name="audiobookshelf-${build}.apk"
          mv -v app-debug.apk "${name}"

      - name: upload app
        uses: actions/upload-artifact@v4
        with:
          name: audiobookshelf-apk
          path: android/app/build/outputs/apk/debug/*.apk
